/**
 * Deterministic guardrails for the AI assistant.
 *
 * Pre-processing detects sensitive request types so the API can
 * attach structured deferrals. Post-processing strips obvious PII
 * from model output.
 *
 * This is NOT a replacement for Gemini's safety settings — it is a
 * deterministic layer that works even if the model ignores the
 * system prompt.
 */

export type DeferralType = 'eligibility' | 'fraud' | 'loan';

export interface Deferral {
  type: DeferralType;
  href: string;
}

export interface GuardrailResult {
  deferral: Deferral | null;
  /** True if the request is a sensitive type that needs a deferral. */
  isSensitive: boolean;
}

// ── Deferral links (deterministic, never generated by the model) ────────────

const DEFERRAL_LINKS: Record<DeferralType, string> = {
  eligibility: '/schemes',
  fraud: '/check',
  loan: '/loan',
};

// ── Detection patterns ───────────────────────────────────────────────────────

const ELIGIBILITY_PATTERNS = [
  /\bam i eligible\b/i,
  /\beligible for\b/i,
  /\bdo i qualify\b/i,
  /\bqualify for\b/i,
  /\bcheck.*eligibility\b/i,
  /\bmy eligibility\b/i,
];

const FRAUD_PATTERNS = [
  /\bis this (a )?fraud\b/i,
  /\bis this (a )?scam\b/i,
  /\bclassify.*(fraud|scam)\b/i,
  /\bdetect.*(fraud|scam)\b/i,
  /\bcheck.*(fraud|scam)\b/i,
  /\bis this message (fraud|suspicious|safe)\b/i,
];

/**
 * Loan calculation patterns — match requests to COMPUTE or CALCULATE
 * loan-related figures, not educational questions about loans.
 *
 * The distinction: "calculate my EMI" is a calculation request (defer),
 * while "what is EMI?" is educational (answer directly).
 */
const LOAN_CALCULATION_PATTERNS = [
  /\bcalculate\b.*\b(loan|emi|repayment|payment|interest)\b/i,
  /\b(loan|emi|repayment|payment|interest)\b.*\bcalculat/i,
  /\bhow much\b.*\b(emi|repayment|payment)\b/i,
  /\bmonthly\b.*\b(loan|emi|repayment|payment)\b/i,
  /\b(loan|emi|repayment|payment)\b.*\bmonthly\b/i,
];

const INVESTMENT_PATTERNS = [
  /\bshould i invest\b/i,
  /\bis (it|this) (a )?good investment\b/i,
  /\bguaranteed? returns?\b/i,
  /\binvest in\b/i,
  /\bwhere should i (put|invest)\b/i,
];

/**
 * Detect the type of deferral needed for a user message.
 *
 * Returns null for general financial-literacy questions that the
 * assistant can answer directly.
 */
export function detectDeferral(message: string): Deferral | null {
  for (const pattern of ELIGIBILITY_PATTERNS) {
    if (pattern.test(message)) {
      return { type: 'eligibility', href: DEFERRAL_LINKS.eligibility };
    }
  }

  for (const pattern of FRAUD_PATTERNS) {
    if (pattern.test(message)) {
      return { type: 'fraud', href: DEFERRAL_LINKS.fraud };
    }
  }

  for (const pattern of LOAN_CALCULATION_PATTERNS) {
    if (pattern.test(message)) {
      return { type: 'loan', href: DEFERRAL_LINKS.loan };
    }
  }

  return null;
}

/**
 * Check if a message is asking for investment advice.
 *
 * These requests get a safety-oriented response rather than a
 * deferral to a deterministic tool (there is no investment tool).
 */
export function isInvestmentAdviceRequest(message: string): boolean {
  return INVESTMENT_PATTERNS.some((pattern) => pattern.test(message));
}

// ── PII stripping ────────────────────────────────────────────────────────────

const PII_PATTERNS: Array<{ pattern: RegExp; replacement: string }> = [
  // Aadhaar: 12 digits, optionally spaced
  { pattern: /\b\d{4}[\s-]?\d{4}[\s-]?\d{4}\b/g, replacement: '[Aadhaar redacted]' },
  // Bank account: 9-18 digits
  { pattern: /\b\d{9,18}\b/g, replacement: '[account redacted]' },
  // OTP: 4-8 digit codes near "OTP" or "code", with optional "is" between
  { pattern: /\b(otp|code)\b[\s:]*(?:is[\s:]*)?\d{4,8}\b/gi, replacement: '[OTP redacted]' },
  // UPI ID
  { pattern: /\b[\w.\-]+@[\w\-]+(?:\.\w+)?\b/g, replacement: '[UPI redacted]' },
];

/**
 * Strip obvious PII from model output.
 *
 * Applied post-generation. This is a best-effort deterministic
 * layer — the system prompt already instructs the model not to
 * echo PII, and the API never logs raw messages.
 */
export function stripPII(text: string): string {
  let result = text;
  for (const { pattern, replacement } of PII_PATTERNS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}
